### ISSUE TITLE
Add name parameter parsing in commands

### ISSUE THREAD

**Issue by jusleg** [jusleg/slackify#11]
Instead of having a regex with all the parameters being ordered, we should also support named parameters so that we can reorder the parameters. We would still have a regex for the action matching, but then we also make sure that the arguments are there and of the proper type before calling the command.

https://gist.github.com/yoshrote/f24f84c1e010a1296f1178849ef5ef34

**Comment by DougEdey** [comment]
Merged with #12 and #17
